// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf7eQfyMNbCs926-TyWkcO4BDvRBBMEQg',
    appId: '1:763008973172:web:9408ff2861a61941485421',
    messagingSenderId: '763008973172',
    projectId: 'fitnessapp-99682',
    authDomain: 'fitnessapp-99682.firebaseapp.com',
    storageBucket: 'fitnessapp-99682.firebasestorage.app',
    measurementId: 'G-EYW5YK8ZDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0fPTqQiGHtRzJxdC4Fd4l-3xjLtP476c',
    appId: '1:763008973172:android:16a9576455a051eb485421',
    messagingSenderId: '763008973172',
    projectId: 'fitnessapp-99682',
    storageBucket: 'fitnessapp-99682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK6_YTFaM9kho2TCll0czWYhk72mIpbU0',
    appId: '1:763008973172:ios:bbddc52bce356385485421',
    messagingSenderId: '763008973172',
    projectId: 'fitnessapp-99682',
    storageBucket: 'fitnessapp-99682.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK6_YTFaM9kho2TCll0czWYhk72mIpbU0',
    appId: '1:763008973172:ios:bbddc52bce356385485421',
    messagingSenderId: '763008973172',
    projectId: 'fitnessapp-99682',
    storageBucket: 'fitnessapp-99682.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf7eQfyMNbCs926-TyWkcO4BDvRBBMEQg',
    appId: '1:763008973172:web:7fdcf0104a1fe1fa485421',
    messagingSenderId: '763008973172',
    projectId: 'fitnessapp-99682',
    authDomain: 'fitnessapp-99682.firebaseapp.com',
    storageBucket: 'fitnessapp-99682.firebasestorage.app',
    measurementId: 'G-NHJKLT8DE3',
  );
}
